export const USER_FETCH = "USER_FETCH";
export const USER_CHANGE_PROFILE = "USER_CHANGE_PROFILE";
export const USER_CHANGE_AVATAR = "USER_CHANGE_AVATAR";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const USER_GET_BY_ID = "USER_GET_BY_ID";
export const USER_SEARCH = "USER_SEARCH";